[package]
name = "keycodemap"
version = "0.1.0"
authors = ["Marc-Andr√© Lureau <marcandre.lureau@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.10"
